apiVersion: v2
name: anjana
description: Tool designed to make the anonymization of sensitive data easier and more intuitive. The app leverages the Anjana Python library for data anonymization.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/jupyter.png
keywords:
  - Anonymization
# home: https://jupyter.org/
# sources:
#   - https://github.com/InseeFrLab/images-datascience
#   - https://github.com/InseeFrLab/helm-charts-interactive-services
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.4.3
dependencies:
  - name: library-chart
    version: 1.7.4
    repository: https://sftobias.github.io/helm-charts-interactive-services
